<div id="panel">
    <h2> Welcome to Your Dashboard, Admin! Let's manage, create, and elevate your blog!</h2>
    <div id="stats">
        <p>You have :</p>
        <p><span  class="number"><?=$articleNumber?> </span>articles</p>
        <p><span class="number"><?=$messagesNumber?></span> messages</p>
        <p><span class="number"><?=$commentsNumber?></span> comments</p>
    </div>
    <div id="">
        <a href="index.php?action=adminProfile"><p>Manage your profile</p></a>
        
    </div>
    <div id="writeArticle">
        <a href="index.php?action=writeArticle"><p>Write an article</p></a>
        
    </div>
    <div id="messages">
        <a href="index.php?action=messages"><p>Manage Messages</p></a> 
    </div>
    <div id="manageArticle">
        <a href="index.php?action=tools"><p>Manage Articles</p></a>
        
    </div>
    <div id="manageComment">
        <a href=""><p>Manage Comments</p></a>
        
    </div>
</div>