
<section>
    <h1 class="header">Welcome, Blog Master! Time to manage your content and inspire the world!</h1>

    <form method="post" id='signUP' action="index.php?action=adminSignIn">
        <label for="email">Email: </label>
        <input type="email" name="email" id="email" placeholder="Email" required>
        <label for="password">Password: </label>
        <input type="password" name="password" id="password" placeholder="Password" required>
        <input type="submit" value="submit" class="primary-btn">
    </form>
</section>
