<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <meta name="description" content="<?= htmlspecialchars($description, ENT_QUOTES, 'UTF-8') ?>" />
    <!-- <meta name="google-site-verification" content="<?= htmlspecialchars($google_site_verification, ENT_QUOTES, 'UTF-8') ?>" /> -->
    <link rel="icon" type="image/ico" href="css/images/logoTitle.png" />
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
    <header>
    <?php if (isset($_SESSION['connected']) && $_SESSION['connected'] === 'connected' && $_SESSION['statusMember'] === 'admin' ) : ?>
        
            <a href="index.php?action=adminLogOut"><span class="logout">Logout</span></a>

    <?php endif;?>
    </header>
    
    <main>
        <?php include htmlspecialchars($template, ENT_QUOTES, 'UTF-8') . ".phtml" ?>
    </main>
</body>