<?php if ($_SERVER["REQUEST_METHOD"] === "POST") : ?>
    <p id="actionComment">
        <?= htmlspecialchars($action, ENT_QUOTES, 'UTF-8') ?><br>
        <a href="index.php?action=home"><button>Go Home</button></a>
    </p>
<?php endif; ?>

<form class="editMessage" action="index.php?action=contact" method="post">
    <legend>Get in Touch! I’d love to hear from you.</legend>
    <p>
    Have feedback, questions, or advice to share? Reach out, and I’ll get back to you as soon as possible!
    </p>
    <p>Fields marked with <span class="important">*</span> are required.</p>
    <fieldset>
        <span><?= htmlspecialchars($errorName, ENT_QUOTES, 'UTF-8') ?></span>
        <label for="name">Your First name <span class="important">&#42;</span></label>
        <input type="text" name="name" id="firstName" value="<?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?>">

        <span><?= htmlspecialchars($errorMail, ENT_QUOTES, 'UTF-8') ?></span>
        <label for="mail">Your Email<span class="important">&#42;</span></label>
        <input type="email" name="email" id="mail" value="<?= htmlspecialchars($email, ENT_QUOTES, 'UTF-8') ?>">
        
        <span></span>
        <label for="subject">Subject</label>
        <input type="text" name="subject" id="subject" value="">

        <span><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></span>
        <label for="message">Your message <span class="important">&#42;</span></label>
        <textarea name="message" id="message" cols="30" rows="20"><?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8') ?></textarea>
        
        <label for="csrf_token"><span><?= htmlspecialchars($errorToken, ENT_QUOTES, 'UTF-8') ?></span></label>
        
        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES, 'UTF-8') ?>">

        <input type="submit" name="submit" value="Send" class="primary-btn">
    </fieldset>
</form>