<?php if ($_SERVER["REQUEST_METHOD"] === "POST") : ?>
    <p id="actionComment">
        <?= htmlspecialchars($action, ENT_QUOTES, 'UTF-8') ?><br>
        <a href="index.php?action=home"><button>Go Home</button></a>
    </p>
<?php endif; ?>

<form class="editMessage" action="index.php?action=contact" method="post">
    <legend>Write a Message</legend>
    <p>
        Want to give feedback, ask for information, or offer advice? Feel free to contact me, and I will respond as soon as possible!
    </p>
    <p>Fields marked with * are required.</p>
    <fieldset>
        <label for="name">Your First name &#42;<span><?= htmlspecialchars($errorName, ENT_QUOTES, 'UTF-8') ?></span></label>
        <input type="text" name="name" id="firstName" value="<?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?>">

        <label for="mail">Your Email &#42;<span><?= htmlspecialchars($errorMail, ENT_QUOTES, 'UTF-8') ?></span></label>
        <input type="email" name="email" id="mail" value="<?= htmlspecialchars($email, ENT_QUOTES, 'UTF-8') ?>">

        <label for="subject">Subject</label>
        <input type="text" name="subject" id="subject" value="">

        <label for="message">Your message &#42;<span><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></span></label>
        <textarea name="message" id="message" cols="30" rows="20"><?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8') ?></textarea>
        
        <label for="csrf_token"><span><?= htmlspecialchars($errorToken, ENT_QUOTES, 'UTF-8') ?></span></label>
        
        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES, 'UTF-8') ?>">

        <input type="submit" name="submit" value="Send">
    </fieldset>
</form>