<section class="tools">
	<h3>Your Favorite Articles: Saved and Ready for You!</h3>
	<?php if (
		htmlspecialchars($_SESSION['connected']) === "connected"
		&& array_key_exists('error', $_GET) && htmlspecialchars($_GET['error']) === "exist"
	) : ?>
		<p>This article is already in your favorites!</p>
	<?php endif; ?>
	<?php if (array_key_exists('success', $_GET) && htmlspecialchars($_GET['success']) === 'success'): ?>
		<p>The article has been successfully removed from your list of favorite articles.</p>
	<?php endif; ?>

	<?php
	// Check if $articles is defined and is an array
	if (!isset($favorites) || !is_array($favorites) || count($favorites) === 0) : ?>
		<p>Your favorites list is empty! Start adding articles you love.</p>
	<?php endif; ?>
	<table>
		<tbody>

			<?php foreach ($favorites as $favorite): ?>

				<tr>
					<td>
						<a title="click to visit" href=<?= htmlentities($favorite['url']) ?>> <?= htmlentities($favorite['title']) ?></a>
						<a href="index.php?action=deleteFavorite&&favoriteId=<?= intval($favorite['id']) ?>"><i class="fas fa-trash-alt" title="delete from favorite"></i></a>

					</td>


				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<a href="index.php?action=home" title="backward to home"><button class="tertiary-btn"> back to home</button></a>
</section>