

<div id="signUP">
	<div>
        <?php if (isset($_GET['comment'])): ?>
            <?php switch ($_GET['comment']): 
                case "inexistent": ?>
                    <p id="actionComment">This email is not associated with an account. If you want to register, please click the button below:</p>
                    <a href="index.php?action=register"><button>Register</button></a>
                    <?php break; 
                case "success": ?>
                    <p id="actionComment">Check your inbox for instructions to reset your password.</p>
                    <?php break; 
                case "invalidEmail": ?>
                    <p id="actionComment">The email address you entered is invalid.</p>
                    <?php break; 
                default: ?>
                    <p id="actionComment">An unknown error occurred. Please try again.</p>
            <?php endswitch; ?>
        <?php endif; ?>
    </div>
	<form method="post" action="index.php?action=forgottenPassword">
		<legend>Please enter your email to reset your password</legend>

		<input type="email" name="email" id="email" placeholder="Email" required>
		<span id="errorMail" class="errorRegister"></span>

		<input type="submit" name="submit" id="submit" value="submit">
	</form>
</div>

