

<div class="forms-style">
    <?php if(isset($_GET["comment"])&& $_GET['comment']==="inexistent") :?>
        <p class="actionComment">This email is not associated with an account. If you want to register, please click the button below:</p>
        <a href="index.php?action=register" class="secondary-btn"><button>Register</button></a>

    
    <?php else:?>
	<div>
        <?php if (isset($_GET['comment'])): ?>
            <?php switch ($_GET['comment']): 
                case "success": ?>
                    <p class="actionComment">Check your inbox for instructions to reset your password.</p>
                    <?php break; 
                case "invalidEmail": ?>
                    <p class="actionComment">The email address you entered is invalid.</p>
                    <?php break; 
                default: ?>
                    <p class="actionComment">An unknown error occurred. Please try again.</p>
            <?php endswitch; ?>
        <?php endif; ?>
    </div>
	<form method="post" action="index.php?action=forgottenPassword" id="forgottenPasswordForm">
		<legend>Please enter your email to reset your password</legend>
        <span id="errorMail" class="errorRegister"></span>
		<input type="email" name="email" id="email" placeholder="Email" >
		

		<input type="submit"  value="submit" class="primary-btn">
	</form>
</div>
<?php endif;?>
