<div id="signUP">

	<?php if (isset($_SESSION['connected']) && $_SESSION['connected'] === "connected") : ?>
		<p id="connected">Hi folk! You are already connected </p>
	<?php else : ?>
		<div id="formLogin">
			<?php if (isset($_GET['error'])) : ?>
				<p id="errorForm">
					<?php
					switch (htmlspecialchars($_GET['error'])) {
						case 'invalid':
							echo 'Incorrect email or password';
							break;
						case 'invalidMail':
							echo 'Invalid email';
							break;
						default:
							echo '';
					}
					?>
				</p>
			<?php endif; ?>
			<p>Already have an account? Log in with your email address and password to pick up where you left off!</p>
			<form method="post" action="index.php?action=signIn" onsubmit=" return login()">
				<input type="email" name="email" id="mail" placeholder="Email" required>
				<input type="password" name="password" id="password" placeholder="Password" required>
				<input type="submit" name="submit" id="submit" value="Login " class="primary-btn">
			</form>
			<div>
				
				<a href="index.php?action=register">
					<!-- <button id="register" class="secondary-btn">Register</button> -->
					<p>New here and ready to join the family? Click here to register and get started!</p>
				</a>
			</div>
			<a href="index.php?action=forgottenPassword">
				<p>Forgot your password? Click here to reset it and regain access!</p>
			</a>


		</div>
	<?php endif; ?>
</div>