<section id="comments">
	
	<?php if (count($messages) === 0) : ?>
		<h3>Your inbox is empty! Check back later for new messages.</h3>
		<a href="index.php?action=adminHomePage" title="Back to Admin Dashboard" class="link"><i class="fas fa-backward"></i>Back to Admin Dashboard</a>
	<?php else : ?>
		<h2>&#47;&#47; Messages : <?= htmlspecialchars($number, ENT_QUOTES, 'UTF-8') ?></h2>
		<a href="index.php?action=adminHomePage" title="Back to Admin Dashboard" class="link"><i class="fas fa-backward"></i>Back to Admin Dashboard</a>
		<?php foreach ($messages as $message) : ?>
			<article>
				
				<span class="messageInfo">From: <?= htmlentities($message['email']) ?></span>
				<span class="messageInfo">Date & Time: <?= htmlentities($message['subject']) ?> <?= htmlentities($message['timeDate']) ?></span>
				<h4><?= htmlentities($message['firstName']) ?> sent : </h4>
				<p><?= htmlentities($message['content']) ?></p>

				<?php if (array_key_exists('statusMember', $_SESSION) && $_SESSION['statusMember'] == 'admin') : ?>
					<a href="index.php?action=<?php echo 'deleteMessage' ?>&&message=<?= intval($message['id']) ?>"><i class="fas fa-trash-alt"></i></a>
				<?php endif; ?>

			</article>
			<!--for underline-->
			<div></div>
		<?php endforeach; ?>
	<?php endif; ?>
</section>