<section id="comments">
	<h2>&#47;&#47; Messages</h2>
	<?php if (count($messages) === 0) : ?>
		<h3>No messages for <?= htmlentities($_SESSION['name'], ENT_QUOTES, 'UTF-8') ?></h3>
	<?php else : ?>
		<?php foreach ($messages as $message) : ?>
			<article>
				<h3><?= htmlentities($message['firstName']) ?> : </h3>
				<span><?= htmlentities($message['email']) ?></span>
				<h4><?= htmlentities($message['subject']) ?> <?= htmlentities($message['timeDate']) ?></h4>
				<p><?= htmlentities($message['content']) ?></p>

				<?php if (array_key_exists('statusMember', $_SESSION) && $_SESSION['statusMember'] == 'admin') : ?>
					<a href="index.php?action=<?php echo 'deleteMessage' ?>&&message=<?= intval($message['id']) ?>"><i class="fas fa-trash-alt"></i></a>
				<?php endif; ?>

			</article>
			<!--for underline-->
			<div></div>
		<?php endforeach; ?>
	<?php endif; ?>
</section>