<div id="signUP">
	<?php if(isset($_GET['comment']) && $_GET['comment'] ==="success") :?>
		<p id="actionComment">congratulations you password is reset, you can connect now</p>
		<a href="index.php?action=login">
			<button class="primary-btn">Login</button>
		</a>
	<?php else : ?>
		<form method="post" action="index.php?action=resetPassword" onsubmit=" return validateFormResetPassword()">
			<legend>Please enter your mail and your new password</legend>

			<input type="email" name="email" id="email" placeholder="email" required>
			<span id="errorMail" class="errorRegister"></span>

			<input type="password" name="password" id="password" placeholder="password" required>
			<span id="errorPassword" class="errorRegister"></span>

			<input type="password" name="passConfirm" id="passConfirm" placeholder="confirm password">
			<span id="errorPasswordC" class="errorRegister"></span>
			
			<input type="submit" name="submit" id="submit" value="submit"  class="primary-btn">
		</form>
	<?php endif;?>
</div>