<div class="forms-style">
	<?php if(isset($_GET['comment']) && $_GET['comment'] ==="success") :?>
		<p class="actionComment">congratulations you password is reset, you can connect now</p>
		<a href="index.php?action=login">
			<button class="primary-btn">Login</button>
		</a>
	
	<?php else : ?>
		<?php if(isset($_GET['comment']) && $_GET['comment'] ==="errorMail") : ?>
			<p class="actionComment">This Email doesn't have an account, please check again !</p>
		<?php elseif(isset($_GET['comment']) && $_GET['comment'] ==="emptyForm") :?>
			<p class="actionComment">Please fill out all fields in the form !</p>
		<?php endif;?>
		<form method="post" action="index.php?action=resetPassword"  id="resetPasswordForm">
			<legend>Please enter your mail and your new password</legend>
			<label for="">Email:</label>
			<span id="errorMail" class="errorRegister"></span>
			<input type="email" name="email" id="emailAccount" placeholder="email" required>
			<label for="">Password:</label>
			<span id="errorPassword" class="errorRegister"></span>
			<input type="password" name="password" id="password" placeholder="password" required>
			<label for="">Confirm your password: </label>
			<span id="errorPasswordC" class="errorRegister"></span>
			<input type="password" name="passConfirm" id="passConfirm" placeholder="confirm password">
			
			
			<input type="submit"  value="submit"  class="primary-btn">
		</form>
	<?php endif;?>
</div>