<section id="post">
	<article>
		<h2>&#60;&#47; <?= htmlentities($article['title'], ENT_QUOTES, 'UTF-8') ?>&#62; </h2>
		<span>
			<i class="far fa-clock"></i> <?= htmlentities($article['timeDate'], ENT_QUOTES, 'UTF-8') ?>
			by <?= ucwords(htmlentities($article['writer'], ENT_QUOTES, 'UTF-8')) ?>
		</span>

		<?php if (!empty($article['image'])) : ?>
			<img src="<?= htmlentities($article['image'], ENT_QUOTES, 'UTF-8') ?>" alt="this is an image">
		<?php endif; ?>

		<div id="share">
			<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a>
			<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
		</div>
		<p id="article2"><?= htmlentities($article['content'], ENT_QUOTES, 'UTF-8') ?></p>
		<p id="article"></p>
		<?php if ($checkUserConnected) : ?>
			<a href="index.php?action=addFavorite&&title=<?= urlencode(htmlentities($article['title'], ENT_QUOTES, 'UTF-8')) ?>&&favoriteId=<?= urlencode(intval($article['id'])) ?>">
				<button title="save the article to read it after">save</button>
			</a>
		<?php else : ?>
			<button title="save the article to read it after" id="save">save</button>
		<?php endif; ?>
		<a href="index.php?action=home"><button>home page</button></a>
	</article>
</section>

<section id="comments">
	<h2>&#47;&#47; Comments : <?= htmlentities($commentNumber['commentNumber'], ENT_QUOTES, 'UTF-8') ?></h2>
	<button id="showComment">click here to comment</button>
	<?php if (isset($_GET['error']) && $_GET['error'] === "commentFailed") : ?>
		<p id="actionComment">It looks like something went wrong with your comment. Please try submitting it again.</p>
	<?php elseif (isset($_GET['success']) && $_GET['success'] === "commentSuccess") : ?>
		<p id="actionComment">Your comment has been posted successfully. Thank you for your feedback!</p>
	<?php endif; ?>

	<form class="editMessage" action="index.php?action=addComment" method="post">
		<legend>&#47;&#8727; Write your comment &#8727;&#47;</legend>
		<fieldset>
			<label for="name">your name</label>
			<input type="text" name="name" id="name" value="<?= isset($_SESSION['name']) ? htmlentities($_SESSION['name'], ENT_QUOTES, 'UTF-8') : '' ?>" placeholder="Enter your name">

			<label for="message">your comment</label>
			<textarea id="message" name="message" id="name"></textarea>

			<input type="hidden" name="articleId" id="name" value="<?= intval($_GET['articleId']) ?>">

			<?php if (isset($_SESSION['id'])) : ?>
				<input type="hidden" name="userId" value="<?= intval($_SESSION['id']) ?>">
			<?php endif; ?>

			<input type="submit" name="submit" value="Submit">
		</fieldset>
	</form>

	<?php foreach ($comments as $comment) : ?>
		<article>
			<h3><?= htmlentities($comment['name'], ENT_QUOTES, 'UTF-8') ?></h3>
			<h4><?= htmlentities($comment['timeDate'], ENT_QUOTES, 'UTF-8') ?></h4>
			<p><?= htmlentities($comment['content'], ENT_QUOTES, 'UTF-8') ?></p>

			<?php if ($checkUserStatus) : ?>
				<a href="index.php?action=deleteComment&&commentId=<?= urlencode(intval($comment['id'])) ?>&&articleId=<?= urlencode(intval($comment['article_Id'])) ?>">
					<i class="fas fa-trash-alt"></i>
				</a>
			<?php endif; ?>

			<?php if (isset($_SESSION['id']) && intval($_SESSION['id']) === intval($comment['comment_Id'])) : ?>
				<a href="index.php?action=deleteComment&commentId=<?= urlencode(intval($comment['id'])) ?>&articleId=<?= urlencode(intval($comment['article_Id'])) ?>">
					<i class="fas fa-trash-alt"></i>
				</a>
			<?php endif; ?>
		</article>
		<!-- for underline-->
		<div></div>
	<?php endforeach; ?>

</section>