<section id="post">
	<article>
		<h2>&#60;&#47; <?= htmlspecialchars($article['title'], ENT_QUOTES, 'UTF-8') ?>&#62; </h2>
		<span>
			<i class="far fa-clock"></i> <?= htmlspecialchars($article['timeDate'], ENT_QUOTES, 'UTF-8') ?>
			by <?= ucwords(htmlspecialchars($article['writer'], ENT_QUOTES, 'UTF-8')) ?>
		</span>

		<?php if (!empty($article['image'])) : ?>
			<img src="<?= htmlspecialchars($article['image'], ENT_QUOTES, 'UTF-8') ?>" alt="this is an image">
		<?php endif; ?>
		<p id="article2"><?= htmlspecialchars($article['content'], ENT_QUOTES, 'UTF-8') ?></p>
		<p id="article"></p>
		<div id="X-share">
			<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button " data-show-count="false" title="share on X">Tweet</a>
			<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
		</div>
		<button class="showComment primary-btn">comment</button>
		<?php if ($checkUserConnected) : ?>
			<a href="index.php?action=addFavorite&title=<?= urlencode($article['title']) ?>&&favoriteId=<?= intval($article['id']) ?>">
				<button title="save the article to read it after" class="secondary-btn"> Bookmark </button></a>
		<?php else : ?>
			<button title="save the article to read it after" class="secondary-btn save">Bookmark</button>
		<?php endif; ?>
		<a href="index.php?action=home#homePage"><button class="tertiary-btn">Explore All Articles</button></a>
	</article>
</section>

<section id="comments">
	<h2>&#47;&#47; Comments : <?= htmlspecialchars($commentNumber['commentNumber'], ENT_QUOTES, 'UTF-8') ?></h2>
	<?php if (isset($_GET['error']) && $_GET['error'] === "commentFailed") : ?>
		<p class="actionComment">It looks like something went wrong with your comment. Please try submitting it again.</p>
	<?php elseif (isset($_GET['success']) && $_GET['success'] === "commentSuccess") : ?>
		<p class="actionComment">Thank you for your feedback!</p>
	<?php endif; ?>

	<form action="index.php?action=addComment" method="post" id="commentSection">
		<?php if ($checkUserConnected) : ?>
			<input type="hidden" name="name" id="name" value="<?= isset($_SESSION['name']) ? htmlspecialchars($_SESSION['name'], ENT_QUOTES, 'UTF-8') : '' ?>" />
			<span id="errorComment" class="errorRegister"></span>
			<textarea id="comment" name="message" placeholder="&#47;&#8727;  Hi <?= htmlspecialchars($_SESSION['name'], ENT_QUOTES, 'UTF-8') ?> ! Share your thoughts! I’d love to hear what you have to say ! &#8727;&#47;"></textarea>
		<?php endif; ?>
		<input type="hidden" name="articleId" id="name" value="<?= intval($_GET['articleId']) ?>">

		<?php if (isset($_SESSION['id'])) : ?>
			<input type="hidden" name="userId" value="<?= intval($_SESSION['id']) ?>">
		<?php endif; ?>

		<input type="submit" name="submit" value="Submit" class="primary-btn">
	</form>

	<?php foreach ($comments as $comment) : ?>
		<article>
			<h3><?= htmlspecialchars($comment['name'], ENT_QUOTES, 'UTF-8') ?> <span> <?= htmlspecialchars($comment['timeDate'], ENT_QUOTES, 'UTF-8') ?></span></h3>
			<p><?= htmlspecialchars($comment['content'], ENT_QUOTES, 'UTF-8') ?></p>

			<?php if ($checkUserStatus) : ?>
				<a href="index.php?action=deleteComment&&commentId=<?= urlencode(intval($comment['id'])) ?>&&articleId=<?= urlencode(intval($comment['article_Id'])) ?>">
					<i class="fas fa-trash-alt"></i>
				</a>
			<?php endif; ?>

			<?php if (isset($_SESSION['id']) && intval($_SESSION['id']) === intval($comment['comment_Id'])) : ?>
				<a href="index.php?action=deleteComment&commentId=<?= urlencode(intval($comment['id'])) ?>&articleId=<?= urlencode(intval($comment['article_Id'])) ?>">
					<i class="fas fa-trash-alt" title="click here to delete your message"></i>
				</a>
			<?php endif; ?>
		</article>
		<!-- for underline-->
		<div></div>
	<?php endforeach; ?>

</section>