<section id="resume">
    <article>
        <p>
            Are you a code newbie? Did you leave a promising career to dive into the tech world, without any programming basics, and face daily skepticism from your entourage? Good news, me too!
        </p>
        <p>
            My name is Nada. Here, I share my daily experiences as a newbie developer with you!
        </p>
    </article>
</section>
