<section id="resume">
    <article>
        <h3>Who Am I ?</h3>
        <p>👋 Hi, I am <span>Nada</span>, I embarked on the journey of "the creating bug" 😉 since 2019 💻 with a pinch of creativity 🎨 and multidisciplinary thinking 🧠</p>
        <p>The first time I saw a computer, I felt a wave of excitement moving through my whole body. Something whispered to me that exploring this machine, unlike any other, would open the door to the highest level of complexity and challenge me intellectually in a way that makes me thrive. 🌟 Endless circumstances drifted us apart, but all the paths I took were just bringing me back to it. Curious to know how? 🔍 What better way than a video to tell you my story? 🎥</p>
        <video controls>
            <source src="css/videos/journey.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <p>Through this blog, I will walk you through my unconventional journey into the enigmatic world of coding—the ups, the downs, the doubts, the slammed doors, the hopes, and the disappointments. Along the way, I’ll share lessons that go beyond technical skills, touching every aspect of my life. Ready to join the ride?</p>
        <!-- <p>
            Are you a code newbie? Did you leave a promising career to dive into the tech world, without any programming basics, and face daily skepticism from your entourage? Good news, me too!
        </p>
        <p>
            My name is Nada. Here, I share my daily experiences as a newbie developer with you!
        </p> -->
    </article>
</section>
